### ISSUE TITLE
Problems with multi-def (local...)

### ISSUE THREAD

**Issue by schanzer** [ds26gte/pyret-lang#11]
`(local [(define x 1)] 2)` works just fine

`(local [(define x 1)  (define y 2)] 3)` results in:
`An unexpected error occurred: TypeError: Cannot read property 'name' of undefined`

**Comment by ds26gte** [comment]
Fixed in 0daaca2 and ds26gte/code.pyret.org@56b4926.

**Comment by schanzer** [comment]
Confirmed fixed!
