### ISSUE TITLE
Nested boolean binops don't translate correctly

### ISSUE THREAD

**Issue by schanzer** [ds26gte/pyret-lang#15]
`(and (and true false) true)` works perfectly, but
`(or (and true false) true)` generates the following error:
`Cannot mix binary operators of different types:`or`and`and`. Use parentheses to disambiguate.`

**Comment by ds26gte** [comment]
Fixed in ds26gte/code.pyret.org@e1fc3b6.

**Comment by schanzer** [comment]
Confirmed fixed!
