### ISSUE TITLE
Weird errors from functions with question marks

### ISSUE THREAD

**Issue by Emmay** [ds26gte/pyret-lang#22]
Not sure if we want to allow question marks (huh??) in function names, but the short program:
(define (safe-left? x) 
  (> x 60))
throws: ReferenceError: Invalid left-hand side in assignment

A longer game file defines the function gameover?, uses it below the definition, but throws the error: 
The name gameoverƎQUESTION is used but not defined at
(this error may be related to #9 )

**Comment by ds26gte** [comment]
Fixed in ds26gte/code.pyret.org@f67ad78.

(Yes, we do want to allow  question marks ("huhn?") in function names, and in all Spyret identifiers in general, and not just at the end of the identifier.)

**Comment by schanzer** [comment]
Sweet! Let's close this.
