### ISSUE TITLE
Problems with else clause

### ISSUE THREAD

**Issue by schanzer** [ds26gte/pyret-lang#23]
Possibly related to recent changes, since I'm sure I would have seen this before...

`(define (sign n)
  (cond [(< n 0) -1]
        [else 1]))`

results in `The name true is used but not defined at...`

**Comment by ds26gte** [comment]
Fixed in ds26gte/code.pyret.org@f1fb23e.

We were desugaring `else` inside `cond` to the literal `true`, and so the special post-desugaring `else` treatment wasn't being exercised at all. And `true` is also no longer a literal, so perfect storm happened.

Removed the desugaring.

**Comment by schanzer** [comment]
Awesome - thanks for moving so quickly!
