### ISSUE TITLE
variadic image primitives aren't variatic

### ISSUE THREAD

**Issue by schanzer** [ds26gte/pyret-lang#3]
(define img (circle 15 "solid" "red"))
(beside img img img)

**Comment by ds26gte** [comment]
Fixed in 192612a.

`overlay`, `underlay`, `above`, `beside`, `overlay/align`, `underlay/align`, `above/align`, `beside/align` now take any number of image arguments instead of just two.

**Comment by schanzer** [comment]
Awesome!! Note that there's some discussion of this in the native library, over at https://github.com/brownplt/pyret-lang/issues/633
