### ISSUE TITLE
Booleans display as #f or #t

### ISSUE THREAD

**Issue by Emmay** [ds26gte/pyret-lang#6]
Should return true or false, eventually.

**Comment by ds26gte** [comment]
While this can be done, is it not confusing that something that can be a valid lexical variable (i.e. `true`, `false`, e.g., in the expression `(lambda (true) true)` which is the identify function) also be used as a quasi-literal? Currently, `true` and `false` are global variables bound to the literals `#t` and `#f`. Would `#true` and `#false` be OK?

**Comment by Emmay** [comment]
Sure, I'd be OK with #true and #false.

**Comment by ds26gte** [comment]
Fixed in ds26gte/code.pyret.org@bd03404. Boolean values now render as `#true` and `#false`.

**Comment by schanzer** [comment]
Awesome. Can one of you close the issue? I don't seem to have access
