### ISSUE TITLE
Transformed Identifiers leaking through for un-spaced binop errors

### ISSUE THREAD

**Issue by schanzer** [ds26gte/pyret-lang#9]
`3+4` should produce something readable. Instead, we get:
`The name Ǝ3ƎPLUS4 is used but not defined at`

When an identifier error is raised, I don't suppose there's a way to look back at the source location and grab the pre-pyretized identifier?

**Comment by ds26gte** [comment]
Fixed in ds26gte/code.pyret.org@3c22ade.

**Comment by schanzer** [comment]
[](url)
